name: movie_finder
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  go_router: ^6.0.1
  google_fonts: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.2.0
  shimmer: ^2.0.0
  sizer: ^2.0.15
  stream_transform: ^2.1.0
  supabase_flutter: ^1.0.1
  transparent_image: ^2.0.0
  youtube_player_flutter: ^8.1.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/animations/
    - .env
